;;; siesta-keywords.el --- SIESTA FDF keywords, units etc.  Used for font-lock and completion.

;; Author: Oliver Strickson <ots22@cam.ac.uk>
;; Created: 14 Sep 2012
;; Keywords: languages

;; Part of FDF Mode for Emacs

(provide 'siesta-keywords)

(defvar siesta-keywords '("LongOutput"
			  "SystemName"
			  "SystemLabel"
			  "NumberOfSpecies"
			  "NumberOfAtoms"
			  "PAO.BasisType"
			  "PAO.BasisSize"
			  "PAO.EnergyShift"
			  "PAO.SplitNorm"
			  "PAO.SplitNormH"
			  "PAO.NewSplitCode"
			  "PAO.FixSplitTable"
			  "PAO.SplitTailNorm"
			  "PAO.SoftDefault"
			  "PAO.SoftInnerRadius"
			  "PAO.SoftPotential"
			  "PAO.OldStylePolOrbs"
			  "FilterCutoff"
			  "FilterTol"
			  "User.Basis"
			  "User.Basis.NetCDF"
			  "WriteIonPlotFiles"
			  "BasisPressure"
			  "Reparameterize.Pseudos"
			  "New.A.Parameter"
			  "New.B.Parameter"
			  "Rmax.Radial.Grid"
			  "Restricted.Radial.Grid"
			  "LatticeConstant"
			  "AtomicCoordinatesFormat"
			  "AtomCoorFormatOut"
			  "ZM.UnitsLength"
			  "ZM.UnitsAngle"
			  "WriteMDHistory"
			  "WriteCoorXmol"
			  "WriteCoorCerius"
			  "WriteMDXmol"
			  "MD.UseSaveXV"
			  "UseStructFile"
			  "MD.UseStructFile"
			  "MD.UseSaveZM"
			  "MD.TypeOfRun"
			  "WarningMinimumAtomicDistance"
			  "MaxBondDistance"
			  "kgrid_cutoff"
			  "ChangeKgridInMD"
			  "WriteKpoints"
			  "XC.functional"
			  "XC.authors"
			  "SpinPolarized"
			  "NonCollinearSpin"
			  "FixSpin"
			  "TotalSpin"
			  "SingleExcitation"
			  "Harris_functional"
			  "MaxSCFIterations"
			  "SCFMustConverge"
			  "DM.MixingWeight"
			  "DM.NumberPulay"
			  "DM.Pulay.Avoid.First.After.Kick"
			  "DM.PulayOnFile"
			  "DM.NumberBroyden"
			  "DM.Broyden.Cycle.On.Maxit"
			  "DM.Broyden.Variable.Weight"
			  "DM.NumberKick"
			  "DM.KickMixingWeight"
			  "DM.MixSCF1"
			  "DM.UseSaveDM"
			  "DM.FormattedFiles"
			  "DM.FormattedInput"
			  "DM.FormattedOutput"
			  "DM.InitSpinAF"
			  "DM.AllowReuse"
			  "DM.AllowExtrapolation"
			  "SCF.Read.Charge.NetCDF"
			  "SCF.Read.Deformation.Charge.NetCDF"
			  "WriteDM"
			  "WriteDM.NetCDF"
			  "WriteDMHS.NetCDF"
			  "WriteDM.History.NetCDF"
			  "WriteDMHS.History.NetCDF"
			  "DM.Tolerance"
			  "DM.Require.Energy.Convergence"
			  "DM.Energy.Tolerance"
			  "DM.Require.Harris.Convergence"
			  "DM.Harris.Tolerance"
			  "MeshCutoff"
			  "MeshSubDivisions"
			  "EggBoxScale"
			  "NeglNonoverlapInt"
			  "SaveHS"
			  "FixAuxiliaryCell"
			  "NaiveAuxiliaryCell"
			  "SolutionMethod"
			  "NumberOfEigensystems"
			  "Use.New.Diagk"
			  "Diag.DivideAndConquer"
			  "Diag.AllInOne"
			  "Diag.NoExpert"
			  "Diag.PreRotate"
			  "Diag.Use2D"
			  "WriteEigenvalues"
			  "OccupationFunction"
			  "OccupationMPOrder"
			  "ElectronicTemperature"
			  "ON.functional"
			  "ON.MaxNumIter"
			  "ON.etol"
			  "ON.eta"
			  "ON.eta_alpha"
			  "ON.eta_beta"
			  "ON.RcLWF"
			  "ON.ChemicalPotential"
			  "ON.ChemicalPotentialUse"
			  "ON.ChemicalPotentialRc"
			  "ON.ChemicalPotentialTemperature"
			  "ON.ChemicalPotentialOrder"
			  "ON.LowerMemory"
			  "ON.UseSaveLWF"
			  "BandLineScale"
			  "WriteKBands"
			  "WriteBands"
			  "WriteFuncKPointsScale"
			  "WriteWaveFunctions"
			  "ProjectedDensityOfStates"
			  "PDOS.kgrid_cutoff"
			  "PDOS.kgrid_Monkhorst_Pack"
			  "LocalDensityOfStates"
			  "WriteMullikenPop"
			  "MullikenInSCF"
			  "COOP.Write"
			  "WFS.EnergyMin"
			  "WFS.EnergyMax"
			  "OpticalCalculation"
			  "Optical.EnergyMinimum"
			  "Optical.EnergyMaximum"
			  "Optical.Broaden"
			  "Optical.Scissor"
			  "Optical.NumberOfBands"
			  "Optical.OffsetMesh"
			  "Optical.PolarizationType"
			  "BornCharge"
			  "NetCharge"
			  "SimulateDoping"
			  "SlabDipoleCorrection"
			  "SaveRho"
			  "SaveDeltaRho"
			  "SaveElectrostaticPotential"
			  "SaveNeutralAtomPotential"
			  "SaveTotalPotential"
			  "SaveIonicCharge"
			  "SaveTotalCharge"
			  "SaveInitialChargeDensity"
			  "MM.Cutoff"
			  "MM.UnitsEnergy"
			  "MM.UnitsDistance"
			  "MM.Grimme.D"
			  "MM.Grimme.S6"
			  "BlockSize"
			  "ProcessorY"
			  "Diag.Memory"
			  "Diag.ParallelOverK"
			  "UseDomainDecomposition"
			  "UseSpatialDecomposition"
			  "RcSpatial"
			  "AllocReportLevel"
			  "UseSaveData"
			  "WriteDenchar"
			  "MD.VariableCell"
			  "MD.ConstantVolume"
			  "MD.RelaxCellOnly"
			  "MD.MaxForceTol"
			  "MD.MaxStressTol"
			  "MD.NumCGSteps"
			  "MD.MaxCGDispl"
			  "MD.PreconditionVariableCell"
			  "ZM.ForceTolLength"
			  "ZM.ForceTolAngle"
			  "ZM.MaxDisplLength"
			  "ZM.MaxDisplAngle"
			  "MD.UseSaveCG"
			  "MD.Broyden.History.Steps"
			  "MD.Broyden.Cycle.On.Maxit"
			  "MD.Broyden.Initial.Inverse.Jacobian"
			  "MD.FIRE.TimeStep"
			  "MD.Quench"
			  "MD.FireQuench"
			  "MD.TargetPressure"
			  "MD.RemoveIntraMolecularPressure"
			  "MD.InitialTimeStep"
			  "MD.FinalTimeStep"
			  "MD.LengthTimeStep"
			  "MD.InitialTemperature"
			  "MD.TargetTemperature"
			  "MD.NoseMass"
			  "MD.ParrinelloRahmanMass"
			  "MD.AnnealOption"
			  "MD.TauRelax"
			  "MD.BulkModulus"
			  "WriteCoorInitial"
			  "WriteCoorStep"
			  "WriteForces"
			  "WriteMDHistory"
			  "MD.FCDispl"
			  "MD.FCfirst"
			  "MD.FCLast")
  "List of SIESTA keywords. See also SIESTA-BLOCK-KEYWORDS.")

;; keywords for begin/end blocks
(defvar siesta-block-keywords '("ChemicalSpeciesLabel"
				"AtomicMass"
				"PAO.BasisSizes"
				"PS.lmax"
				"PS.KBprojectors"
				"PAOBasis"
				"LatticeParameters"
				"LatticeVectors"
				"SuperCell"
				"AtomicCoordinatesOrigin"
				"AtomicCoordinatesAndAtomicSpecies"
				"ZMatrix"
				"kgrid_Monkhorst_Pack"
				"XC.Hybrid"
				"DM.InitSpin"
				"GridCellSampling"
				"EggboxRemove"
				"BandLines"
				"BandPoints"
				"WaveFuncKPoints"
				"Optical.Mesh"
				"Optical.Vector"
				"PolarizationGrids"
				"ExternalElectricField"
				"MM.Potentials"
				"MD.TargetStress"
				"GeometryConstraints"
				"PhononLabels"
				"MD.ATforPhonon")
  "List of SIESTA keywords taking a data block. See also SIESTA-KEYWORDS.")

;; additional keywords from TranSIESTA
(defvar transiesta-keywords '("TS.SaveHS"
			      "TS.Voltage"
			      "TS.MixH"
			      "TS.UpdatedMCROnly"
			      "TS.CalcGF"
			      "TS.TriDiag"
			      "TS.HSFileLeft"
			      "TS.GFFileLeft"
			      "TS.HSFileRight"
			      "TS.GFFileRight"
			      "TS.NumUsedAtomsLeft"
			      "TS.NumUsedAtomsRight"
			      "TS.BufferAtomsLeft"
			      "TS.BufferAtomsRight"
			      "TS.ComplexContour.Emin"
			      "TS.ComplexContour.NumCircle"
			      "TS.ComplexContour.NumLine"
			      "TS.ComplexContour.NumPoles"
			      "TS.BiasContour.Eta"
			      "TS.BiasContour.Method"
			      "TS.BiasContour.NumPoints"
			      "TS.TBT.HSfile"
			      "TS.TBT.Emin"
			      "TS.TBT.Emax"
			      "TS.TBT.NPoints"
			      "TS.TBT.NEigen")
  "Keywords for TRANSIESTA.")

(defvar siesta-units '("Kg"
		       "g"
		       "amu"
		       "m"
		       "nm"
		       "Ang"
		       "Bohr"
		       "s"
		       "fs"
		       "J"
		       "erg"
		       "eV"
		       "meV"
		       "Ry"
		       "mRy"
		       "Hartree"
		       "K"
		       "kcal/mol"
		       "N"
		       "eV/Ang"
		       "Ry/Bohr"
		       "cm"
		       "ps"
		       "ns"
		       "mHartree"
		       "kJ/mol"
		       "Hz"
		       "THz"
		       "cm-1"
		       "cm^-1"
		       "Pa"
		       "MPa"
		       "GPa"
		       "atm"
		       "bar"
		       "Mbar"
		       "C"
		       "e"
		       "C*m"
		       "D"
		       "debye"
		       "e*Bohr"
		       "e*Ang"
		       "cm**-1"
		       "Ry/Bohr**3"
		       "eV/Ang**3"
		       "Kg*m**2"
		       "Ry*fs**2"
		       "V/m"
		       "V/nm"
		       "V/Ang"
		       "V/Bohr"
		       "Ry/Bohr/e"
		       "Har/Bohr/e"
		       "deg"
		       "rad"
		       "eV/deg"
		       "eV/rad"
		       "Ry/deg"
		       "Ry/rad"
		       "meV/deg"
		       "meV/rad"
		       "mRy/deg"
		       "mRy/rad"
		       "mins"
		       "hours"
		       "days")
  "List of units available to SIESTA")

(defvar siesta-strings
  '("split" "SplitGauss" "nodes" "nonodes"
    "SZ" "DZ" "SZP" "DZP"
    "NotScaledCartesianBohr" "NotScaledCartesianAng" "ScaledCartesian"
    "LDA" "LSD" "GGA"
    "ca" "pw92" "pbe" "revpbe" "rpbe" "wc" "pbesol" "lyp"
    "diagon" "ordern" "transiesta"
    "fd" "mp"
    "kim" "ordejon-mauri" "files"
    "pi/a" "ReciprocalLatticeVectors"
    "polarized" "unpolarized" "polycrystal"
    "CG" "Broyden"
    "Temperature" "Pressure" "TemperatureAndPressure"
    "Sommerfield" "GaussFermi"
    "Molecule" "Cartesian" "Constants" "Variables" "Constraint"
    "cellside" "cellangle" "stress" "position" "center" "rigid" "routine"))

